### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by majsan** [spraakbanken/karp-s-backend#5]
Each resource gets a list of tags ["saohist", "hist"] for example

`/config` returns the available tags with label:
```
saolhist:
  label: SAOLHist
hist:
  label:
    eng: Historical lexicons
    swe: Historiska lexikon
```
